GitHub app
mongoosejs/backend pull request #2
Opened 2021-10-06 21:14 UTC by IslandRhythms

So according to the docs and my runs, you don't need a token to get the organization members https://docs.github.com/en/rest/reference/orgs#list-organization-members
However, to see private members of an organization, the app must also be a member of the org you are looking up and be authenticated. I don't know how to overcome that hurdle. Does installing the app automatically make the app and member of the org?

2021-10-08 16:09 UTC, vkarpov15 requested changes

2021-10-08 16:09 UTC, vkarpov15 commented on webhookGithubApp/index.js
> +    id: ,
Pull these from `config` please

2021-10-08 16:09 UTC, vkarpov15 commented on webhookGithubApp/index.js
> +  if(installation.account.type == 'Organization') {
Make this a `if(installation.account.type !== 'Organization') { return; }` and move it up to before `createAppAuth()` to we can avoid extra indentation and not unnecessarily create app auth if we don't need it.

2021-10-08 16:09 UTC, vkarpov15 commented on webhookGithubApp/index.js
> +      await Subscriber.create({
Let's create an array of `githubOrgMembers` instead of creating a separate subscriber for every member. So one subscriber per GitHub org.

2021-10-12 21:38 UTC, IslandRhythms commented on webhookGithubApp/index.js
> +      await Subscriber.create({
so change the schema to only have `githubOrgMembers: []` and `githubOrganization` and `githubOrganizationId` and then
create that in the database?

2021-11-11 19:01 UTC, vkarpov15 approved these changes
Gonna merge this for now and make a few fixes in master

2021-11-11 19:01 UTC, merged